server:
  port: 8900

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: all-in-web
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/