eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8600
spring:
  application:
    name: service-zuul
zuul:
  routes:
    all-in-web:
      path: /all-in-we/**
      serviceId: all-in-web
    all-in-school:
      path: /all-in-school/**
      serviceId: all-in-school
